import type { CaseRecord, User, OrgUnit } from './types'

export const CASES: CaseRecord[] = [
  {
    id: 'FHC-2026-001',
    subject: 'Housing Application',
    customer: 'Abebe Kebede',
    customerPhone: '0911-234-567',
    customerEmail: 'abebe.kebede@email.com',
    customerAddress: 'Addis Ababa, Bole Sub-City, Woreda 03',
    sector: 'Housing Development',
    directorate: 'Directorate A',
    group: 'Group A1',
    status: 'In Progress',
    isArchived: false,
    priority: 'High',
    date: 'Aug 15, 2026',
    lastActivity: '2h ago',
    reference: 'REF-2026-1034',
    documents: [
      { name: 'Housing_Application.pdf', size: '2.4 MB', date: 'Aug 15', version: 1, type: 'main' },
      { name: 'National_ID.pdf', size: '890 KB', date: 'Aug 15', version: 1, type: 'attachment' },
      { name: 'Supporting_Document.pdf', size: '1.1 MB', date: 'Aug 15', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 15, 09:00 AM', remark: 'Case registered and documents uploaded.' },
      { stage: 'Housing Development Sector', actor: 'Yonas Tesfaye', status: 'done', timestamp: 'Aug 15, 10:15 AM', remark: 'Assigned to Directorate A.' },
      { stage: 'Directorate A', actor: 'Meron Alemu', status: 'done', timestamp: 'Aug 15, 11:30 AM', remark: 'Assigned to Group A1 for review.' },
      { stage: 'Group A1', actor: 'Daniel Girma', status: 'active', timestamp: 'Aug 15, 12:00 PM' },
      { stage: 'Directorate A', actor: '', status: 'pending', timestamp: '' },
      { stage: 'Housing Development Sector', actor: '', status: 'pending', timestamp: '' },
    ],
    remarks: [
      { author: 'Directorate A', role: 'Directorate', timestamp: 'Aug 15, 11:30 AM', content: 'Please verify the applicant\'s supporting documentation thoroughly.' },
      { author: 'Group A1', role: 'Group', timestamp: 'Aug 15, 12:45 PM', content: 'Documents received. Currently under detailed review.' },
    ],
  },
  {
    id: 'FHC-2026-002',
    subject: 'Land Allocation Request',
    customer: 'Tigist Worku',
    customerPhone: '0922-345-678',
    customerEmail: 'tigist.worku@email.com',
    customerAddress: 'Addis Ababa, Kirkos Sub-City, Woreda 07',
    sector: 'Housing Development',
    directorate: 'Directorate B',
    group: 'Group B1',
    status: 'Approved',
    isArchived: false,
    priority: 'Normal',
    date: 'Aug 14, 2026',
    lastActivity: '1d ago',
    reference: 'REF-2026-1029',
    documents: [
      { name: 'Land_Request.pdf', size: '1.8 MB', date: 'Aug 14', version: 1, type: 'main' },
      { name: 'Title_Deed.pdf', size: '560 KB', date: 'Aug 14', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 14, 09:00 AM' },
      { stage: 'Housing Development Sector', actor: 'Yonas Tesfaye', status: 'done', timestamp: 'Aug 14, 10:00 AM' },
      { stage: 'Directorate B', actor: 'Liya Bekele', status: 'done', timestamp: 'Aug 14, 11:00 AM' },
      { stage: 'Group B1', actor: 'Henok Assefa', status: 'done', timestamp: 'Aug 14, 02:00 PM' },
      { stage: 'Directorate B', actor: 'Liya Bekele', status: 'done', timestamp: 'Aug 14, 04:00 PM' },
      { stage: 'Housing Development Sector', actor: 'Yonas Tesfaye', status: 'done', timestamp: 'Aug 14, 05:00 PM', remark: 'Approved.' },
    ],
    remarks: [],
  },
  {
    id: 'FHC-2026-003',
    subject: 'Service Connection Application',
    customer: 'Dawit Mulugeta',
    customerPhone: '0933-456-789',
    customerEmail: 'dawit.m@email.com',
    customerAddress: 'Addis Ababa, Yeka Sub-City, Woreda 11',
    sector: 'Corporate Service',
    directorate: 'Directorate C',
    group: 'Group C1',
    status: 'Rejected',
    isArchived: false,
    priority: 'Normal',
    date: 'Aug 13, 2026',
    lastActivity: '2d ago',
    reference: 'REF-2026-1015',
    reason: 'The required supporting documentation was incomplete. The applicant must submit a valid utility bill and proof of residence.',
    documents: [
      { name: 'Service_Application.pdf', size: '1.2 MB', date: 'Aug 13', version: 1, type: 'main' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 13, 09:00 AM' },
      { stage: 'Corporate Service Sector', actor: 'Hana Girma', status: 'done', timestamp: 'Aug 13, 10:00 AM', remark: 'Rejected — insufficient documentation.' },
    ],
    remarks: [
      { author: 'Corporate Service Sector', role: 'Sector', timestamp: 'Aug 13, 10:00 AM', content: 'Missing utility bill and proof of residence. Rejecting per FHC policy.' },
    ],
  },
  {
    id: 'FHC-2026-004',
    subject: 'Construction Input Supply Request',
    customer: 'Biruk Tadesse',
    customerPhone: '0944-567-890',
    customerEmail: 'biruk.t@email.com',
    customerAddress: 'Addis Ababa, Nifas Silk Sub-City, Woreda 05',
    sector: 'Construction Input Supply',
    directorate: 'Directorate A',
    group: 'Group A2',
    status: 'Returned',
    isArchived: false,
    priority: 'High',
    date: 'Aug 15, 2026',
    lastActivity: '4h ago',
    reference: 'REF-2026-1040',
    documents: [
      { name: 'Supply_Request.pdf', size: '3.1 MB', date: 'Aug 15', version: 2, type: 'main' },
      { name: 'Project_Plan.pdf', size: '4.5 MB', date: 'Aug 15', version: 1, type: 'attachment' },
      { name: 'Budget_Summary.pdf', size: '780 KB', date: 'Aug 15', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 15, 08:00 AM' },
      { stage: 'Construction Input Supply Sector', actor: 'Fekadu Woldemariam', status: 'done', timestamp: 'Aug 15, 09:00 AM' },
      { stage: 'Directorate A', actor: 'Meron Alemu', status: 'done', timestamp: 'Aug 15, 10:00 AM' },
      { stage: 'Group A2', actor: 'Selamawit Hailu', status: 'active', timestamp: 'Aug 15, 11:00 AM' },
    ],
    remarks: [
      { author: 'Directorate A', role: 'Directorate', timestamp: 'Aug 15, 10:00 AM', content: 'Additional budget justification needed before final recommendation.' },
    ],
  },
  {
    id: 'FHC-2026-005',
    subject: 'House Administration Transfer',
    customer: 'Selam Tesfaye',
    customerPhone: '0955-678-901',
    customerEmail: 'selam.t@email.com',
    customerAddress: 'Addis Ababa, Kolfe Sub-City, Woreda 08',
    sector: 'Houses Administration',
    directorate: 'Directorate B',
    group: 'Group B2',
    status: 'Pending Clarification',
    isArchived: false,
    priority: 'Normal',
    date: 'Aug 12, 2026',
    lastActivity: '3d ago',
    reference: 'REF-2026-1008',
    documents: [
      { name: 'Transfer_Request.pdf', size: '1.5 MB', date: 'Aug 12', version: 1, type: 'main' },
      { name: 'Previous_Owner_ID.pdf', size: '450 KB', date: 'Aug 12', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 12, 09:00 AM' },
      { stage: 'Houses Administration Sector', actor: 'Almaz Bekele', status: 'done', timestamp: 'Aug 12, 10:30 AM' },
      { stage: 'Directorate B', actor: 'Liya Bekele', status: 'done', timestamp: 'Aug 12, 02:00 PM' },
      { stage: 'Group B2', actor: 'Naol Girma', status: 'active', timestamp: 'Aug 12, 03:00 PM' },
    ],
    remarks: [
      { author: 'Group B2', role: 'Group', timestamp: 'Aug 13, 09:00 AM', content: 'Awaiting clarification on previous ownership documentation from the applicant.' },
    ],
  },
  {
    id: 'FHC-2026-006',
    subject: 'Cooperative Housing Registration',
    customer: 'Meseret Alemu',
    customerPhone: '0966-789-012',
    customerEmail: 'meseret.a@email.com',
    customerAddress: 'Addis Ababa, Akaky Sub-City, Woreda 02',
    sector: 'Housing Development',
    directorate: 'Directorate A',
    group: 'Group A1',
    status: 'New',
    isArchived: false,
    priority: 'Normal',
    date: 'Aug 15, 2026',
    lastActivity: '30m ago',
    reference: 'REF-2026-1045',
    documents: [
      { name: 'Cooperative_Registration.pdf', size: '2.0 MB', date: 'Aug 15', version: 1, type: 'main' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 15, 02:30 PM' },
      { stage: 'Housing Development Sector', actor: '', status: 'active', timestamp: '' },
    ],
    remarks: [],
  },
  {
    id: 'FHC-2026-007',
    subject: 'Infrastructure Project Application',
    customer: 'Yihenew Hailu',
    customerPhone: '0977-890-123',
    customerEmail: 'yihenew.h@email.com',
    customerAddress: 'Addis Ababa, Gullele Sub-City, Woreda 01',
    sector: 'Construction Input Supply',
    directorate: 'Directorate B',
    group: 'Group B1',
    status: 'Delayed',
    isArchived: false,
    priority: 'High',
    date: 'Aug 03, 2026',
    lastActivity: '12d ago',
    reference: 'REF-2026-0987',
    documents: [
      { name: 'Infrastructure_Application.pdf', size: '5.2 MB', date: 'Aug 03', version: 1, type: 'main' },
      { name: 'Site_Survey.pdf', size: '8.1 MB', date: 'Aug 03', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 03, 09:00 AM' },
      { stage: 'Construction Input Supply Sector', actor: 'Fekadu Woldemariam', status: 'done', timestamp: 'Aug 03, 10:00 AM' },
      { stage: 'Directorate B', actor: 'Liya Bekele', status: 'done', timestamp: 'Aug 03, 02:00 PM' },
      { stage: 'Group B1', actor: 'Henok Assefa', status: 'active', timestamp: 'Aug 04, 09:00 AM' },
    ],
    remarks: [
      { author: 'Directorate B', role: 'Directorate', timestamp: 'Aug 10, 11:00 AM', content: 'This case has been idle for over a week. Please expedite the review.' },
    ],
  },
  {
    id: 'FHC-2026-008',
    subject: 'Residential Plot Assignment',
    customer: 'Rahel Tesfaye',
    customerPhone: '0988-901-234',
    customerEmail: 'rahel.t@email.com',
    customerAddress: 'Addis Ababa, Lideta Sub-City, Woreda 04',
    sector: 'Housing Development',
    directorate: 'Directorate C',
    group: 'Group C1',
    status: 'Archived',
    isArchived: false,
    priority: 'Normal',
    date: 'Aug 05, 2026',
    lastActivity: '10d ago',
    reference: 'REF-2026-0990',
    documents: [
      { name: 'Plot_Assignment.pdf', size: '1.7 MB', date: 'Aug 05', version: 1, type: 'main' },
      { name: 'Survey_Map.pdf', size: '2.3 MB', date: 'Aug 05', version: 1, type: 'attachment' },
    ],
    timeline: [
      { stage: 'Records & Archive', actor: 'Sara Haile', status: 'done', timestamp: 'Aug 05, 09:00 AM' },
      { stage: 'Housing Development Sector', actor: 'Yonas Tesfaye', status: 'done', timestamp: 'Aug 05, 10:00 AM' },
      { stage: 'Directorate C', actor: 'Kebede Girma', status: 'done', timestamp: 'Aug 05, 01:00 PM' },
      { stage: 'Group C1', actor: 'Tsion Bekele', status: 'done', timestamp: 'Aug 06, 10:00 AM' },
      { stage: 'Directorate C', actor: 'Kebede Girma', status: 'done', timestamp: 'Aug 07, 09:00 AM' },
      { stage: 'Housing Development Sector', actor: 'Yonas Tesfaye', status: 'done', timestamp: 'Aug 07, 02:00 PM', remark: 'Approved and archived.' },
    ],
    remarks: [],
  },
]

export const USERS: User[] = [
  { id: '1', name: 'Yonas Tesfaye', username: 'yonas.t', email: 'yonas@fhc.gov.et', role: 'sector', unit: 'Housing Development Sector', status: 'Active' },
  { id: '2', name: 'Meron Alemu', username: 'meron.a', email: 'meron@fhc.gov.et', role: 'directorate', unit: 'Directorate A — Housing Development', status: 'Active' },
  { id: '3', name: 'Daniel Girma', username: 'daniel.g', email: 'daniel@fhc.gov.et', role: 'group', unit: 'Group A1 — Directorate A', status: 'Active' },
  { id: '4', name: 'Sara Haile', username: 'sara.h', email: 'sara@fhc.gov.et', role: 'records', unit: 'Records & Archive', status: 'Active' },
  { id: '5', name: 'Hana Girma', username: 'hana.g', email: 'hana@fhc.gov.et', role: 'sector', unit: 'Corporate Service Sector', status: 'Active' },
  { id: '6', name: 'Liya Bekele', username: 'liya.b', email: 'liya@fhc.gov.et', role: 'directorate', unit: 'Directorate B — Housing Development', status: 'Active' },
  { id: '7', name: 'Henok Assefa', username: 'henok.a', email: 'henok@fhc.gov.et', role: 'group', unit: 'Group B1 — Directorate B', status: 'Active' },
  { id: '8', name: 'Fekadu W.', username: 'fekadu.w', email: 'fekadu@fhc.gov.et', role: 'sector', unit: 'Construction Input Supply Sector', status: 'Active' },
  { id: '9', name: 'Almaz Bekele', username: 'almaz.b', email: 'almaz@fhc.gov.et', role: 'sector', unit: 'Houses Administration Sector', status: 'Inactive' },
  { id: '10', name: 'System Admin', username: 'admin', email: 'admin@fhc.gov.et', role: 'admin', unit: 'System Administration', status: 'Active' },
]

export const ORG_UNITS: OrgUnit[] = [
  { id: 's1', name: 'Housing Development Sector', type: 'sector', active: 24, pending: 5, delayed: 4 },
  { id: 's2', name: 'Corporate Service Sector', type: 'sector', active: 11, pending: 2, delayed: 1 },
  { id: 's3', name: 'Houses Administration Sector', type: 'sector', active: 8, pending: 3, delayed: 2 },
  { id: 's4', name: 'Construction Input Supply Sector', type: 'sector', active: 15, pending: 4, delayed: 3 },
  { id: 'd1', name: 'Directorate A', type: 'directorate', parent: 's1', active: 8, pending: 2, delayed: 1 },
  { id: 'd2', name: 'Directorate B', type: 'directorate', parent: 's1', active: 10, pending: 2, delayed: 2 },
  { id: 'd3', name: 'Directorate C', type: 'directorate', parent: 's1', active: 6, pending: 1, delayed: 1 },
  { id: 'd4', name: 'Directorate A', type: 'directorate', parent: 's2', active: 6, pending: 1, delayed: 0 },
  { id: 'd5', name: 'Directorate B', type: 'directorate', parent: 's2', active: 5, pending: 1, delayed: 1 },
  { id: 'g1', name: 'Group A1', type: 'group', parent: 'd1', active: 5, pending: 1, delayed: 0 },
  { id: 'g2', name: 'Group A2', type: 'group', parent: 'd1', active: 3, pending: 1, delayed: 1 },
  { id: 'g3', name: 'Group B1', type: 'group', parent: 'd2', active: 6, pending: 1, delayed: 1 },
  { id: 'g4', name: 'Group B2', type: 'group', parent: 'd2', active: 4, pending: 1, delayed: 1 },
  { id: 'g5', name: 'Group C1', type: 'group', parent: 'd3', active: 6, pending: 1, delayed: 1 },
]

export const AUDIT_LOGS = [
  { id: 1, timestamp: 'Aug 15, 10:32', user: 'System Admin', action: 'User created', entity: 'User: sara.h', type: 'user' },
  { id: 2, timestamp: 'Aug 15, 10:45', user: 'Sara Haile', action: 'Case registered', entity: 'FHC-2026-006', type: 'case' },
  { id: 3, timestamp: 'Aug 15, 11:20', user: 'Meron Alemu', action: 'Case assigned to group', entity: 'FHC-2026-001 → Group A1', type: 'case' },
  { id: 4, timestamp: 'Aug 15, 11:30', user: 'Yonas Tesfaye', action: 'Case assigned to directorate', entity: 'FHC-2026-001 → Directorate A', type: 'case' },
  { id: 5, timestamp: 'Aug 15, 12:10', user: 'Hana Girma', action: 'Case rejected', entity: 'FHC-2026-003', type: 'case' },
  { id: 6, timestamp: 'Aug 15, 13:00', user: 'System Admin', action: 'Organizational unit added', entity: 'Group A2', type: 'org' },
  { id: 7, timestamp: 'Aug 15, 14:15', user: 'Liya Bekele', action: 'Case transferred', entity: 'FHC-2026-007: Dir A → Dir B', type: 'transfer' },
  { id: 8, timestamp: 'Aug 15, 15:00', user: 'Daniel Girma', action: 'Remark added', entity: 'FHC-2026-001', type: 'remark' },
  { id: 9, timestamp: 'Aug 15, 15:45', user: 'System Admin', action: 'Password reset', entity: 'User: almaz.b', type: 'user' },
  { id: 10, timestamp: 'Aug 15, 16:00', user: 'Yonas Tesfaye', action: 'Case approved', entity: 'FHC-2026-008', type: 'case' },
]

export const CHART_DATA = [
  { month: 'Mar', received: 38, approved: 22, rejected: 8 },
  { month: 'Apr', received: 45, approved: 28, rejected: 10 },
  { month: 'May', received: 52, approved: 35, rejected: 9 },
  { month: 'Jun', received: 48, approved: 31, rejected: 11 },
  { month: 'Jul', received: 61, approved: 42, rejected: 12 },
  { month: 'Aug', received: 43, approved: 28, rejected: 7 },
]

export const SECTORS = [
  'Housing Development Sector',
  'Corporate Service Sector',
  'Houses Administration Sector',
  'Construction Input Supply Sector',
]

export const DIRECTORATES_BY_SECTOR: Record<string, string[]> = {
  'Housing Development Sector': ['Directorate A', 'Directorate B', 'Directorate C'],
  'Corporate Service Sector': ['Directorate A', 'Directorate B'],
  'Houses Administration Sector': ['Directorate A', 'Directorate B'],
  'Construction Input Supply Sector': ['Directorate A', 'Directorate B', 'Directorate C'],
}

export const GROUPS_BY_DIRECTORATE: Record<string, string[]> = {
  'Directorate A': ['Group A1', 'Group A2'],
  'Directorate B': ['Group B1', 'Group B2'],
  'Directorate C': ['Group C1'],
}
